Add GitHub widget, close #408
joelshepherd/tabliss pull request #409
Opened 2021-09-25 08:28 UTC by vdimir

<details>
<summary>Screenshot</summary>

<img width="936" alt="image" src="https://user-images.githubusercontent.com/7023786/134764957-a181e25e-4ce9-457f-8f33-af4d77a78377.png">

</details>

2021-12-19 20:31 UTC, vintprox commented
Impressive looking 😁

2021-12-20 15:04 UTC, vdimir commented
And now this PR contains two features for github, this calendar with activity (on the screenshot) and also it can show notifications from github (you need to provide API key for it). Maybe this features should be handled by different widgets or at least be spilled onto two PRs. I use my build of tabliss with couple of patches (that are open PRs in this repo), though.

2022-01-13 06:23 UTC, BreakBB requested changes
Just some small suggestions to improve code consistency. You should also check your prettier settings, because many lines are missing a `;` which should be added by default 🤔

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +        return
```suggestion
    if (!href) {
        return;
    }
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +    let onClick = (e: any) => {
```suggestion
    const onClick = (e: any) => {
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +        let options = { responsive: false, global_stats: data.showActivitySummary, }
```suggestion
        const options = { responsive: false, global_stats: data.showActivitySummary, }
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +    let forceRefreshNotifications = () => cache && setCache({ ...cache, since: cache.since + 1 })
```suggestion
    const forceRefreshNotifications = () => cache && setCache({ ...cache, since: cache.since + 1 })
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +    let openAllNotifications = () => {
```suggestion
    const openAllNotifications = () => {
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +    let hasNotifications = cache?.notifications && (cache?.notifications?.length > 0);
```suggestion
    const hasNotifications = cache?.notifications && (cache?.notifications?.length > 0);
```

2022-01-13 06:23 UTC, BreakBB commented on src/plugins/widgets/github/GitHub.tsx
> +    let href = getNotificationUrl(notification)
```suggestion
    const href = getNotificationUrl(notification)
```

2022-03-11 08:52 UTC, joelshepherd commented
Hi @vdimir, could you move the notification part to a separate PR? Because I will need to update the privacy policy and data declarations if I start storing access tokens in Tabliss, which will take me a while.

And can you run [prettier](https://prettier.io/) over your code to match the code style?

Thanks, your work looks great!

2022-03-11 13:11 UTC, vdimir commented
> Hi @vdimir, could you move the notification part to a separate PR? Because I will need to update the privacy policy and data declarations if I start storing access tokens in Tabliss, which will take me a while.

Ok, now remove this part form current PR, will create new one later.

> And can you run [prettier](https://prettier.io/) over your code to match the code style?

Just with default config? It it is, done.

2022-03-11 15:11 UTC, joelshepherd commented
Yep, default config is good. Thanks, it looks great! It'll be in the next release.

2022-03-11 15:11 UTC, merged

2022-03-11 17:12 UTC, joelshepherd commented
Wow, it looks really good! Nice work.

![image](https://user-images.githubusercontent.com/4484306/157914461-fcce76ae-89f7-4b04-a166-22b9fa2cfd29.png)